insert into bikes.types (type, description)
values ('Road Bike','Road bikes are best identified by their drop or turned-down handlebars and skinny tires. The downward-curving handlebars are usually super lightweight that help put you in an aerodynamic position. The lightweight frame makes this type of bicycle particularly good for numerous pavement uses including racing, touring, fitness riding, long-distance rides and daily commuting. The large, thin tires allow you to glide the bike along various terrains with zero to little effort. If you are supremely concerned about speed, varied options for hand and riding positions, and an efficient transference of energy into propelling the bike forward, a road bike is the best option for you.');
insert into bikes.types (type, description)
values ('Mountain Bike', 'This bike is designed with excellent braking systems and shock-absorbing features that can easily handle serious bumps, rocks, dirt trails, roots and ruts.  Mountain bikes are meant for dealing with steeper terrain which is why most of them consist of lower gears as compared to most other road bikes. They usually have 26-inch or 29-inch wide knobby tires that make them function amazingly well over obstacles and in loose dirt. They also consist of rugged components and frames, flat handlebars and suspension in order to assist cyclists in navigating rocky mountain hills.');
insert into bikes.types (type, description)
values ('Touring Bike', 'These are almost like the traditional road bikes, except with a few tweaks and changes that make them perfect for long-distance bike tours. Touring bikes come with multiple attachment points with the help of which you can attach fenders, pumps, lights, racks, water bottles and so much more. They also contain super sturdy frames that allow them to carry heavy loads on both the front and the rear racks. You must have noticed that in many touring bikes come with a longer wheelbase, which is specially engineered to provide more control to the rider, owing to their lower center of gravity. Majority of touring bikes also consist of disc brakes that provide them with enhanced stopping power, particularly on non-paved surfaces. A defining feature of touring bikes is their wide or semi-knobby tires that are especially designed to handle gravel roads.');
insert into bikes.types (type, description)
values ('Folding Bike', 'Folding bikes are believed to be excellent travel companions. As the name suggests, they fold super easily and smoothly, allowing them to be able to effortlessly fit on a boat, in the trunk of a car or on a subway. They can even be folded and carried in a carrying bag which makes them extremely convenient for commuters who have limited storage space at home or elsewhere. A few overriding features of folding bikes include smaller wheels, with most of them being 20-inches, making it easy for the bike  to get over bumps and potholes in order to provide you with a smooth ride. Another great feature is that they have adjustable functions on the folding frame, handlebar and saddle, all which allow an easier folding process. Many also have adjustable latches that help the bike collapse easily.');
insert into bikes.types (type, description)
values ('Fixed Gear/Track Bike', 'Often referred to as “fixies”, Fixed Gear or Track bikes are primarily used for racers and athletes that are training for professional races. The main reason for this is that as the name aptly suggests, these bikes contain a single, fixed gear, which means that you cannot coast or freewheel on this type of bike. This suggests that cyclists or riders using this bike have to make use of their leg strength in order to stop the cranks of the bike from turning, and further halting its motion. Fixed gear bikes may contain several brakes and varied styles of handlebars and they usually require cyclists to spin their legs in constant circles in order to run a higher cadence.');
insert into bikes.types (type, description)
values ('BMX', 'BMX is an acronym for Bicycle Motor Cross, primarily because this type of bicycle is a single-speed bike that is raced around short dirt tracks, quite similar in nature to the motor sport. The acronym is also often used describe any bike with single-speed and a 20-inch wheel. BMX bikes are ideal for people who intend to perform tricks and jumps with their bikes because they are especially built for that, with their robust and durable design and structure. They consist of small frames, a single gear and twenty inch wheels which means that they are not only strong but very low maintenance too as compared to an average bicycle.');
insert into bikes.types (type, description)
values ('Recumbent Bike', 'This type of bicycle is more popular as a “non-traditional” bicycle because it requires one to sit in a seat that is lower to the ground and looks like a chair. Recumbent bikes consist of different configurations including long to short wheelbases, varieties of two, three or four wheelers, as well as under and above seat steering. These bikes allow for a function similar to doing a seated leg press whereby the cyclist is required to properly rest against the backrest of the bicycle in order to help them turn a larger gear. A defining feature of recumbent bikes often deemed as a drawback is that one cannot stand up while pedaling up a challenging hill because of its form and design.');
insert into bikes.types (type, description)
values ('Cruiser', 'Cruiser bikes come under the umbrella term of “specialty bikes” that contain very specific end uses and features, setting them apart from other types of bikes.  Cruiser bikes are meant for leisurely rides that one would take around the town and their neighborhood. Most of these bikes feature wider 26-inch tires as compared to several other pavement bikes. They consist of comfortable seats that allow for relaxed seating positions, and often also internally geared rear hubs that allow easy and convenient maintenance.');
